version: '3'

services:
  db:
    container_name: swift_cms_db
    image: postgres:15.3-alpine3.18
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - 'docker-swift-cms-postgres:/var/lib/postgresql/data'
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - 'docker-swift-cms-redis:/data'
volumes:
  docker-swift-cms-redis:
  docker-swift-cms-postgres:
